title: "Julien DEPRE"
description: "Personal landing page for Julien DEPRE"
url: "https://dep.re"
baseurl: ""
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

author:
  name: "Julien DEPRE"
  email: "julien@dep.re"

minima:
  skin: solarized

# kramdown defaults
markdown: kramdown
kramdown:
  input: GFM
